# Generated by Django 2.2.3 on 2019-08-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student_org', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('account_num', models.BigIntegerField()),
                ('sub_account_num', models.BigIntegerField()),
                ('dollar_amount', models.BigIntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
