# Generated by Django 2.2.3 on 2019-08-05 04:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generate_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.CharField(blank=True, default='', max_length=100)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('form_response', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='form_model',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
