# Generated by Django 2.2.3 on 2019-08-05 05:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generate_form', '0002_auto_20190805_0424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_Model2',
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='account_num',
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='date',
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='dollar_amount',
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='student_org',
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='sub_account_num',
        ),
        migrations.AddField(
            model_name='form_model',
            name='event_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='form_model',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='form_model',
            name='form_response',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
