# Generated by Django 2.2.3 on 2019-08-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_form', '0003_auto_20190805_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_model',
            name='form_response',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
