# Generated by Django 2.2.3 on 2019-08-08 03:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generate_form', '0004_auto_20190808_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_model',
            name='form_response',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
