# Generated by Django 2.2.3 on 2019-08-08 05:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generate_form', '0006_auto_20190808_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form_model',
            options={'ordering': ('form_response',)},
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='created',
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='form_model',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='form_model',
            name='form_response',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
