# Generated by Django 2.2.3 on 2019-08-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_form', '0007_auto_20190808_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form_model',
            options={},
        ),
    ]
